### ISSUE TITLE
Field "ddl_change_user" contains the owner of _pgpm - should be the user, who issued the command

### ISSUE THREAD

**Issue by FritzLehmann** [affinitas/pgpm#31]
It's enough to use session_user instead of current_user as default for this column.
I could prove that by hacking "ALTER TABLE ... ALTER COLUMN ... SET DEFAULT session_user" - and it worked.

Consider the following:
flehmann=# create function pgpm_test() returns text as $$select current_user::text$$ security definer language sql;
CREATE FUNCTION
flehmann=# select pgpm_test();
 --> flehmann
flehmann=# alter function pgpm_test() owner to postgres;
ALTER FUNCTION
flehmann=# select pgpm_test();
--> postgres

flehmann=# create function pgpm_test1() returns text as $$select session_user::text$$ security definer language sql;
CREATE FUNCTION
flehmann=# select pgpm_test1();
--> flehmann
flehmann=# alter function pgpm_test1() owner to postgres;
ALTER FUNCTION
flehmann=# select pgpm_test1();
--> flehmann

**Comment by megaponchic** [comment]
@FritzLehmann Thanks, should be fixed with new version
