### ISSUE TITLE
allow same ddl-script name in different repositories

### ISSUE THREAD

**Issue by FritzLehmann** [affinitas/pgpm#34]
Sometimes fo rone feature i have to do ddl-changes in 2 (or more) schemas/repos. So my ddl-scripts naturally are named the same (in my case edarling_cid_tracking/ddl/acs_162_flehmann.sql and edarling_dwh_data/ddl/acs_162_flehmann.sql)
When deploying the second, I get "ddl/acs_162_flehmann.sql is not executed for schema edarling_dwh_data as it has already been executed before."
You would probably just add a column "package" to _pgpm.table_evolutions_log and add the package as parameter to _pgpm._is_table_ddl_executed(p_file_name text)

**Comment by megaponchic** [comment]
implemented exactly as you mentioned
